Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pdrake.Models;

namespace pdrake.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pdrake.Models.MovieProject;

namespace pdrake.Controllers
{
    public class MovieController : Controller
    {
        public async Task<ActionResult> GetMovies(int genreId = 0, int page = 1)
        {
            using HttpClient httpClient = new HttpClient();
            if (genreId == 0)
            {
                var apiResponse = await httpClient.GetStreamAsync(
                    "https://api.themoviedb.org/3/discover/movie?api_key=e2e4f004450c3b2d09d61c0fb5120d06&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=true&page=" + page);
                ViewData["movies"] = await JsonSerializer.DeserializeAsync<MovieResults>(apiResponse);
            }

            else
            {
                var apiResponse = await httpClient.GetStreamAsync(
                    "https://api.themoviedb.org/3/discover/movie?api_key=e2e4f004450c3b2d09d61c0fb5120d06&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=true&with_genres=" + genreId + "&page=" + page);
                ViewData["movies"] = await JsonSerializer.DeserializeAsync<MovieResults>(apiResponse);
            }
            return View();
        }

        public async Task<ActionResult> MoviePage(int movieId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                var apiResponse = await httpClient.GetStreamAsync("https://api.themoviedb.org/3/movie/" + movieId + "?api_key=e2e4f004450c3b2d09d61c0fb5120d06&language=en-US");
                var movieProviders = await httpClient.GetStreamAsync("https://api.themoviedb.org/3/movie/" + movieId + "/watch/providers?api_key=e2e4f004450c3b2d09d61c0fb5120d06");
                ViewData["movieProviders"] = await JsonSerializer.DeserializeAsync<Root>(movieProviders);
                ViewData["movieResults"] = await JsonSerializer.DeserializeAsync<Root>(apiResponse);
                return View();
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <title>Paul Drake's Website</title>
</head>
<body>
<header>
    <div class="container">
        <div class="row">
            <div class="col-md-1 col-sm-3">
                <a class=" btn btn-primary" role="button" href="files/Resume 2020.pdf">Resume</a>
            </div>
            <div class="col-sm-11 d-none d-sm-block d-md-none">
                <h6 class="text-center">Paul Drake's Website</h6>
            </div>
            <div class="col-md-8 d-sm-none d-md-block">
                <h3 class="text-center">Paul Drake's Website</h3>
            </div>
            <div class="dropdown col-md-3 col-sm-4">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Projects</button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" asp-controller="Movie" asp-action="GetMovies">Movie Streaming Availability App</a>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <p>I was born and raised in South Florida. I attended Broward College to pursue my passion for science and public service. Broward College has a three year Paramedic program and I graduated in 2012. Studied for the state Paramedic License and recieved my license in 2013. I moved to West Texas with my family in 2013 to be closer to my aging grandparents. In 2015, I started classes at South Plains College and started taking English, Math, and Programing classes. Very quickly I got hooked on programing and coding. I was recruited into the coding program at South Plains College in the Fall of 2019. This programing was an eleven month intensive coding bootcamp. In the ten months, I learned C#, HTML, CSS, MySQL, and Angular.</p>
            </div>
            <div class="col-6 float-right">
                <img class="img-fluid" src="files/_DSC0630-Costco3.jpg" alt="My_Picture">
            </div>
        </div>
    </div>
</main>
</body>
</html>